# Generated by Django 4.1.7 on 2023-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_gallery_alter_service_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
