# Generated by Django 4.1.7 on 2023-03-19 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_dish_is_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='visit_datetime',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('H', ' heart'), ('T', 'tie'), ('HAM', 'hamburger')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number is waited in format +380xx xxx xx xx', regex='^\\+?3?8?0?\\d{2}[ -]?(\\d[ -]?){7}$')]),
        ),
    ]
