# Generated by Django 4.1.7 on 2023-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_date_reservation_visit_datetime_service_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='visit_datetime',
            field=models.DateField(),
        ),
    ]
