# Generated by Django 4.1.7 on 2023-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_reservation_visit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.CharField(max_length=10),
        ),
    ]
