# Generated by Django 4.1.7 on 2023-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_reservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.SmallIntegerField(max_length=10),
        ),
    ]
