# Generated by Django 4.1.7 on 2023-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_reservation_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('H', ' heart'), ('T', 'user-tie'), ('HAM', 'hamburger')], default='H', max_length=3),
        ),
    ]
