# Generated by Django 4.1.7 on 2023-03-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_reservation_guests_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('H', 'far fa-heart'), ('T', 'fas fa-user-tie'), ('HAM', 'fas fa-hamburger')], default='H', max_length=3),
        ),
    ]
